# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [wasmer_llvm]
  pull_request:
    branches: [wasmer_llvm]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install scoop
        shell: pwsh
        run: |
          iwr -useb get.scoop.sh | iex
          refreshenv
          scoop install 7zip curl wget
      - name: Setup
        run: |
          curl -o llvm-11.1.0-windows.zip -L https://github.com/hanabi1224/ci-playground/suites/2139951212/artifacts/43778875
          7z e -y llvm-11.1.0-windows.zip
          set LLVM_SYS_110_PREFIX=%cd%\llvm-11.1.0-windows
          echo %LLVM_SYS_110_PREFIX%
          git clone https://github.com/hanabi1224/wasmer
          pushd wasmer
          git checkout win_llvm
      - name: Build
        run: |
          echo %LLVM_SYS_110_PREFIX%
          pushd wasmer/lib/cli
          cargo build --release --features llvm
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wasmer.exe
          path: wasmer/target/release/wasmer.exe
          if-no-files-found: error
          retention-days: 30
